Start mvp bot
TiunovNN/hse-knee-xray-research pull request #8
Opened 2024-01-06 19:12 UTC by AlexTrigolos

2024-01-08 07:33 UTC, TiunovNN requested changes

2024-01-08 07:33 UTC, TiunovNN commented on tg_bot/src/main.py
> +SHOW_CLASSES = '"' + '", "'.join(CLASSES[:-1]) + f'" or "{CLASSES[-1]}"'
style: 
```python
SHOW_CLASSES = ','.join(map(repr, CLASSES))
```

2024-01-08 07:33 UTC, TiunovNN commented on tg_bot/src/main.py
> +# Commands
style: Такое лучше уносить в docstring:
```python
async def handle_start(message: types.Message):
    """Handler /start
    """
```

2024-01-08 07:33 UTC, TiunovNN commented on tg_bot/src/main.py
> +async def handle_save_training_image(message: types.Message, bot: Bot):
лучше сразу сохранять в  s3.  Для этого можно использовать [aioboto3](https://aioboto3.readthedocs.io/en/latest/usage.html#s3-examples)

```python
from PIL import Image

async def handle_save_training_image(message: types.Message, bot: Bot, s3_client):
    buffer = await bot.download(message.photo[-1])
    buffer.seek(0)
    img = Image.open(buffer)
    name = f'{message.photo[-1].file_unique_id}.{img.format.lower()}'
    buffer.seek(0)
    await s3_client.upload_fileobj(buffer, BUCKET_NAME, f'traindata/{name})
    ....
```

2024-01-08 07:33 UTC, TiunovNN commented on tg_bot/src/main.py
> +async def handle_lots_of_predictions(message: types.Message, state: FSMContext):
лучше заменить на получение архива

2024-01-08 12:36 UTC, AlexTrigolos commented on tg_bot/src/main.py
> +SHOW_CLASSES = '"' + '", "'.join(CLASSES[:-1]) + f'" or "{CLASSES[-1]}"'
А так ли нам тут нужны map и repr? И так же строки.

2024-01-08 13:04 UTC, TiunovNN commented on tg_bot/src/main.py
> +SHOW_CLASSES = '"' + '", "'.join(CLASSES[:-1]) + f'" or "{CLASSES[-1]}"'
Не понял вопроса. Я указал способ сделать эту строку короче

2024-01-08 18:09 UTC, AlexTrigolos commented on tg_bot/src/main.py
> +async def handle_save_training_image(message: types.Message, bot: Bot):
Не смог с этим пока разобраться, могу потом когда-нибудь попробовать, просто так ни разу даже с подобным не работал(

2024-01-08 18:11 UTC, AlexTrigolos commented on tg_bot/src/main.py
> +async def handle_lots_of_predictions(message: types.Message, state: FSMContext):
Не думаю, что это прям так нужно, в предсказаниях и так нормально, сказал бы обрабатывает, объединение можно для отправки нам подумать, но и так не то что бы необходимо это на данный момент. Если нужно, то и этим потом могу попробовать заняться, но пока, считаю в учебе есть более приоритетные задачи.

2024-01-09 06:19 UTC, TiunovNN commented on tg_bot/src/main.py
> +async def handle_lots_of_predictions(message: types.Message, state: FSMContext):
В таком случае эта ручка бессмысленна. Можно сделать одну ручку в которую картинки отправляются и сразу выдается ответ. без дополнительного уровня в меню для предсказаний

2024-01-09 08:05 UTC, TiunovNN approved these changes

2024-01-09 08:23 UTC, merged